//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Punishment
    {
        public int ID { get; set; }
        public Nullable<int> Users { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> Finish { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<int> Action { get; set; }
    
        public virtual Tbl_Action Tbl_Action { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
