//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Book()
        {
            this.Tbl_Action = new HashSet<Tbl_Action>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Category { get; set; }
        public Nullable<int> Author { get; set; }
        public string Production_Year { get; set; }
        public string Publisher { get; set; }
        public string Page { get; set; }
        public Nullable<bool> Check { get; set; }
        public string Book_Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Action> Tbl_Action { get; set; }
        public virtual Tbl_Author Tbl_Author { get; set; }
        public virtual Tbl_Category Tbl_Category { get; set; }
    }
}
